version: 1.0.{build}

image:
  - Visual Studio 2015
  - Ubuntu
  - ubuntu1804

environment:
  PERL5LIB: /home/appveyor/perl5/lib/perl5
  AUTOMATED_TESTING: 1

platform: x64

branches:
  only:
    - master

skip_tags: true

install:
  - cmd: if not exist "C:\strawberry" cinst StrawberryPerl --allow-empty-checksums
  - cmd: path C:\strawberry\perl\bin;C:\strawberry\perl\site\bin;C:\strawberry\c\bin;%PATH%
  # - cmd: cd C:\projects\%APPVEYOR_PROJECT_NAME%
  - sh: sudo apt-get update -q
  - sh: sudo apt-get install -y build-essential git libssl-dev
  - sh: sudo apt-get install -y perl
  - sh: export PATH=/home/appveyor/perl5/bin:$PATH
  - perl -V
  - cmd: mkdir %APPVEYOR_BUILD_FOLDER%\tmp
  - cmd: set TMPDIR=%APPVEYOR_BUILD_FOLDER%\tmp
  - cpan App::cpanminus
  - cpanm -n Dist::Zilla Test::Pod::Coverage
  - dzil authordeps --missing | cpanm -n
  - dzil listdeps --missing | cpanm -n
  - git config --global user.email "njh@bandsman.co.uk"
  - git config --global user.name "Nigel Horne"
  - cmd: 'echo End install at: & time /t'

build: off

test_script:
  - dzil test -v
